### ISSUE TITLE
JSDOM API change breaks virtual console in tests

### ISSUE THREAD

**Issue by ochrons** [scala-js/scala-js#2902]
What used to be
```js
var virtualConsole = jsdom.createVirtualConsole();
```
is now (in JSDOM 10.0.0)
```js
const virtualConsole = new jsdom.VirtualConsole();
```

which makes builds using `npm install jsdom` fail with
```text
[error] [stdin]:40
[error]     virtualConsole: jsdom.createVirtualConsole().sendTo(console),
[error]                           ^
[error] 
[error] TypeError: jsdom.createVirtualConsole is not a function
```

**Comment by ochrons** [comment]
As a workaround, force JSDOM version to latest before 10.0.0 in your (eg.) Travis config
```
  - npm install jsdom@9.12.0
```

**Comment by sjrd** [comment]
Oh seriously ... 😞

**Comment by sjrd** [comment]
`jsdom.createVirtualConsole()` is the only thing that is affected. `jsdom.env` is also broken. This significantly contradicts [the claim of `jsdom`'s doc](https://github.com/tmpvar/jsdom#jsdom) that

> As of v10, jsdom has a new API (documented below). **The old API is still supported for now**; [see its documentation](https://github.com/tmpvar/jsdom/blob/master/lib/old-api.md) for details.

(emphasis mine).

**Comment by sjrd** [comment]
https://github.com/tmpvar/jsdom/issues/1820

**Comment by sjrd** [comment]
Well [I was being dumb](https://github.com/tmpvar/jsdom/issues/1820#issuecomment-297198316). PR available at #2910.

**Comment by sjrd** [comment]
Fixed in #2910.

**Comment by sjrd** [comment]
For those blocked by this issue, 0.6.16 is now available on Maven Central and fixes it. It is not *announced* yet, though, so you won't find release notes or docs. But you can use it to unblock yourselves.

**Comment by zy4** [comment]
/cc @sjrd 
the exact same error came back as an effect of the jsdom 12.0.0 release, I guess. Can somebody verifiy?

**Comment by sjrd** [comment]
Easy: https://github.com/jsdom/jsdom/blob/master/Changelog.md#1200

> Removed the old jsdom API, as the new API now has all the capabilities you need.

We are still using the old API.

Use jsdom 11.x in the meantime.

**Comment by sjrd** [comment]
#3432
