### ISSUE TITLE
Automated tests for the incremental compiler/linker

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#3758]
See https://github.com/scala-js/scala-js/pull/3757#pullrequestreview-282154854

**Comment by gzm0** [comment]
I cannot reproduce the original problem on the master branch. @sjrd could you have a look: 
https://github.com/gzm0/scala-js/tree/inc-test

**Comment by sjrd** [comment]
Hum, but the fix was merged in 0.6.x and then forward merged to master, wasn't it? So it seems quite normal that you wouldn't be able to reproduce it on master, no?

**Comment by gzm0** [comment]
The last commit in that branch reverts the relevant parts of the merge but the test still does not fail.

**Comment by gzm0** [comment]
Ping @sjrd? So the problem here is that even when reverting the fix, I cannot reproduce the problem.

**Comment by sjrd** [comment]
I'm not sure why you can't reproduce it when reverting the fix. Perhaps something related with `scripted`? At least I can reproduce the bug in a standalone project using 0.6.28 or 1.0.0-M8, while it's fixed with 0.6.29.

The minimized repro project has:

`project/build.properties`
```
sbt.version=1.2.8
```

`project/plugins.sbt`
```scala
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.0.0-M8")
```

`build.sbt`
```scala
enablePlugins(ScalaJSPlugin)

name := "Scala.js Tutorial"
scalaVersion := "2.12.8"

// This is an application with a main method
scalaJSUseMainModuleInitializer := true
```

`src/main/scala/tutorial/webapp/TutorialApp.scala`
```scala
package tutorial.webapp

object TutorialApp {
  def main(args: Array[String]): Unit = {
    addClickedMessage()
  }

  @noinline
  def addClickedMessage(): Unit = {
    val d = Data(5)
    println(d.count)
  }
}
```

`src/main/scala/tutorial/webapp/Data.scala`
```scala
package tutorial.webapp

case class Data(count: Int)
```

**Comment by sjrd** [comment]
Oh I see now. You're missing the
```scala
scalaJSUseMainModuleInitializer := true
```
in your scripted test. So `fastOptJS` has nothing to link.
